"""Access key repository protocol."""

from __future__ import annotations

from typing import Protocol

from opensandbox_server.services.access_key_models import AccessKeyRecord


class AccessKeyRepository(Protocol):
    def create(self, record: AccessKeyRecord) -> AccessKeyRecord: ...
    def get(self, key_id: str) -> AccessKeyRecord | None: ...
    def list_all(self) -> list[AccessKeyRecord]: ...
    def update(self, record: AccessKeyRecord) -> AccessKeyRecord: ...
    def delete(self, key_id: str) -> None: ...
